# Generated by Django 4.2 on 2023-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
