# Generated by Django 4.2 on 2023-07-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField()),
                ('is_check', models.BooleanField(default=False)),
                ('data_sent', models.DateTimeField(default=datetime.datetime(2023, 7, 28, 21, 30, 4, 125443))),
            ],
        ),
    ]
