# Generated by Django 4.2 on 2023-07-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_updatecode_data_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecode',
            name='code',
            field=models.CharField(default='123456'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='data_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 15, 33, 41, 431605)),
        ),
    ]
