# Generated by Django 4.2 on 2023-07-19 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_updatecode_data_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecode',
            name='user',
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='data_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 19, 32, 32, 870984)),
        ),
    ]
