# Generated by Django 4.2 on 2023-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(choices=[('like', '👍🏻')], max_length=5),
        ),
    ]
