# Generated by Django 4.2 on 2023-07-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_made_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='made_number',
        ),
    ]
