# Generated by Django 4.2 on 2023-07-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_archived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedPost',
        ),
    ]
