# Generated by Django 4.2 on 2023-08-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('UserSavedData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Saved_post', to='post.post')),
            ],
        ),
    ]
