# Generated by Django 4.2 on 2023-08-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserSavedData', '0004_remove_savedpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
