# Generated by Django 4.2 on 2023-08-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSavedData', '0005_savedpost_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPostSaved',
        ),
    ]
