# Generated by Django 4.2 on 2023-08-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('UserSavedData', '0006_delete_userpostsaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_post', to='post.post'),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
