# Generated by Django 4.2 on 2023-07-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user'),
        ('instaitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Archived',
        ),
    ]
