# Generated by Django 4.2 on 2023-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
