# Generated by Django 4.2 on 2023-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(default='/home/shagi/Downloads/pexels-adrien-olichon-2387793.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
