# Generated by Django 4.2 on 2023-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='story',
            field=models.FileField(default='</home/shagi/Downloads/pexels-adrien-olichon-2387793.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
