# Generated by Django 4.2 on 2023-07-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField()),
                ('is_varification', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
