# Generated by Django 4.2 on 2023-07-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_varificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('see_user', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
