# Generated by Django 4.2 on 2023-07-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userstory_body_userstory_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStoryArchived',
        ),
    ]
