# Generated by Django 4.2 on 2023-08-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_userstoryarchived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
